### ISSUE TITLE
final project feedback

### ISSUE THREAD

**Issue by lvreynoso** [escofresco/makeschool_fsp2_realtweets#4]
Hi Jonasz! I've graded your final project and have some feedback for you:

- good job implementing your Dictogram and Listogram classes and passing all unit tests
- good job with your sampling methods in both classes
- good job implementing a >2nd order Markov chain. I would think more on the data structure you're using to implement higher orders, however; using a `tuple` as a key is easier to reason with at all points in the process of building and generating a Markov chain than highly-nested dictionaries, and there isn't any need for an intermediate step.
- awesome job writing tests for your Markov chain!
- your heroku app only displays one word at a time and does not use a markov chain, please fix
- a good rule of thumb is to keep your code as simple as possible while still implementing all needed functionality. This will help immensely when debugging, building more complex projects and when you're in collaborative situations (which will be the vast majority of your time in industry).

**Comment by escofresco** [comment]
Thanks Lucia. I'm definitely working on taming complexity, which definitely got outta hand with this project. Any advice on how to do is always appreciated.
